spring:
  application:
    name: doctor-appointment-app
  datasource:
    url: jdbc:mysql://localhost:3306/doc_appointment_app
    username: root
    password: hiepbui32
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # Kích thước tối đa của file
      max-request-size: 10MB  # Kích thước tối đa của request
  jwt:
    signerKey: "LD4WdV1y2aghWc5XIjI/aLryDMurH2A3Mj/WRFYYTBdIE1t0CR3l4yytQupbEA4G"
    valid-duration: 3600
    refreshable-duration: 18000
  mail:
    host: smtp.gmail.com
    port: 587 #25
    username: ok.byethibye2@gmail.com
    password: hzdribmtrvoaqcoa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  apiEndpoint: http://localhost:8080

email:
  sender: ok.byethibye2@gmail.com
